### ISSUE TITLE
Swing mode - invalid options shown

### ISSUE THREAD

**Issue by jellewie** [DomiStyle/esphome-panasonic-ac#112]
I installed the module like shown in [here](https://github.com/DomiStyle/esphome-panasonic-ac/issues/111)

My Airco does not have a Horizontal swing mode, I did enable vertical_swing_select since I do have that.
The issue now it that it does show options for horizontal swing:
![image](https://github.com/DomiStyle/esphome-panasonic-ac/assets/1545223/b3fb84cf-51f6-4ce6-a8c9-66808253c69c)
When selected:
Off = Off
Both = changes to Vertical (and does so)
Vertical = just changes to Vertical  (and does so)
Horizontal = Changes to Off (and does so)

It would be more useful if this setting was instead "vertical_swing_select" / "vertical_swing_mode". Can this be chanes, or is this a setting I can adjust?
![image](https://github.com/DomiStyle/esphome-panasonic-ac/assets/1545223/a0bb4b16-6d04-4129-ae16-1812f9c0d6a4)

My EXACT Config:
```
substitutions:
  device_name: "smart-airco-01"
  project_name: "JelleWho.smart-airco"   #By.ProjectName
  project_version: "0.1"                  #Hardware
  project_comment: "Airco beneden"     #Name in ESPhome tab

esphome:
  name: "${device_name}"
  comment: "${project_comment}"
  project:
    name: "${project_name}"
    version: "${project_version}"
esp32:
  board: esp32dev
  framework:
    type: arduino

#web_server:        #[OPTIONAL] Example configuration entry
#logger:            #[OPTIONAL] Enable logging
api:                #Enable Home Assistant API https://esphome.io/components/api.html
  reboot_timeout: 12h
ota:                #Enable Over The Air updates
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:               #Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "${device_name} FH"
  reboot_timeout: 12h
captive_portal:

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  parity: EVEN

external_components:
  source: github://DomiStyle/esphome-panasonic-ac #https://github.com/DomiStyle/esphome-panasonic-ac
  components: [panasonic_ac]

climate:
  - platform: panasonic_ac
    type: cnt # For DNSK-P11 use wlan, For CZ-TACG1 use cnt
    name: "${device_name}"
    #horizontal_swing_select:
    #  name: "${device_name} Swing Mode"
    vertical_swing_select:
      name: "${device_name} Vertical Swing Mode"
    outside_temperature:
      name: "${device_name} Outside Temperature"
    # Enable as needed
    #eco_switch:
    #  name: Panasonic AC Eco Switch
    #econavi_switch:
    #  name: Panasonic AC Econavi Switch
    #nanoex_switch:
    #  name: Panasonic AC NanoeX Switch
    mild_dry_switch:
      name: Panasonic AC Mild Dry Switch
    current_power_consumption:
      name: Panasonic AC Power Consumption

    # Useful when the ac does not report a current temperature (CZ-TACG1 only)
    # current_temperature_sensor: temperature_sensor_id

sensor:
  - platform: uptime  # Extra sensor to keep track of plug uptime
    name: "${device_name} Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 0
    disabled_by_default: true
  - platform: wifi_signal # Extra sensor for WiFi signal
    name: "${device_name} WiFi"
    update_interval: 300s
    disabled_by_default: true

#https://esphome.io/components/light/status_led.html
light:
  - platform: status_led
    name: "${device_name} Status LED"
    disabled_by_default: true
    pin: GPIO2

#https://esphome.io/cookbook/pir.html
binary_sensor:
  - platform: status  # Extra sensor for the connection state
    name: "${device_name} status"
    disabled_by_default: true

text_sensor:
  - platform: wifi_info #https://esphome.io/components/text_sensor/index.html
    ip_address:
      name: ESP IP Address
      disabled_by_default: true
    mac_address:
      name: ESP Mac Wifi Address
      disabled_by_default: true

button:
  - platform: restart
    id: restart_button
    name: "${device_name} Restart"
    disabled_by_default: true

time:
  - platform: sntp
    id: my_time
```

**Comment by riegojerey** [comment]
Have you ever solved this problem?

**Comment by Her0-1337** [comment]
I got the same issue.
I just removed it from the climate card and used a second entity card with the entitys directly from the device.
With this, I also have the option to steer the fins to a specific position.

```
type: entities
entities:
  - entity: >-
      select.arbeitszimmer_klima_arbeitszimmer_klima_arbeitszimmer_vertikale_lamellen
    name: Lamellen
  - entity: switch.klima_arbeitszimmer_nanoex
    name: NanoeX

``` 

<img width="448" height="474" alt="Image" src="https://github.com/user-attachments/assets/c301cb7a-c109-46f8-a28b-c7669e54fe96" />

<img width="448" height="474" alt="Image" src="https://github.com/user-attachments/assets/4d8756f8-1508-4a1d-b239-61db8b554e11" />
