### ISSUE TITLE
Slow/none response sometimes using Pansonic Z35UFEAW-1 (CZ-TACG1)

### ISSUE THREAD

**Issue by jkaberg** [DomiStyle/esphome-panasonic-ac#122]
I'm seeing some erratic behavior on my Pansonic Z35UFEAW-1 (CZ-TACG1) where the heat pump seems to not respond to commands (me changing mode) or an unusual long delay. It's been like this for a year now and been bugging me so thought I'd bring it up. However I don't know howto proceed from here

Config:
```
esphome:
  name: "ac-1-etasje"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: VERBOSE #VERBOSE #DEBUG #INFO

api:
  encryption:
    key: !secret encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  #power_save_mode: none
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 12
  manual_ip:
    static_ip: 10.0.40.13
    gateway: 10.0.40.1
    subnet: 255.255.255.0
    dns1: 10.0.40.1

  ap:
    ssid: "Panasonic AC Fallback Hotspot"
    password: !secret ap_fallback_password

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  parity: EVEN

#esp32_ble_tracker:
#  scan_parameters:
#    interval: 1100ms
#    window: 1100ms
#    active: true

sensor:
  - platform: wifi_signal
    name: "Wifi Signal Strength"
    update_interval: 60s
  - platform: uptime
    name: "Uptime"

#bluetooth_proxy:
#  active: true

external_components:
  - source: 
      type: git
      url: https://github.com/DomiStyle/esphome-panasonic-ac
      #ref: 2.3.0 # command buffering not working?
    components: [panasonic_ac]

climate:
  - platform: panasonic_ac
    type: cnt

    name: Panasonic AC
    vertical_swing_select:
      name: Panasonic AC Vertical Swing Mode
    outside_temperature:
      name: Panasonic AC Outside Temperature
    nanoex_switch:
      name: Panasonic AC NanoeX Switch
    current_power_consumption:
      name: Panasonic AC Power Consumption
```

Logs:
[logs_ac-1-etasje_run.txt](https://github.com/user-attachments/files/16759110/logs_ac-1-etasje_run.txt)
