### ISSUE TITLE
🎉 Tested and Confirmed: Working on an ESP8266 NodeMCUv2 🎉

### ISSUE THREAD

**Issue by Expaso** [DomiStyle/esphome-panasonic-ac#5]
Perhaps not the correct place to share this information, but nice to hear anyway!

I still had some ESP8266 NodeMCUv2's laying around that I wanted to designate to this task. 
But.. as you already suggested, these only have 1 full UART (the second one is TX only).

This is fixable in the ESP Config, by moving the Log component to UART-1 (instead of the default UART-0):

```
# Enable logging
logger:
  hardware_uart: UART1 #Uses D4 (GPIO2) as LOG output!
```

And so we freed up UART-0 for our purpose:

```
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  id: ac_uart
  baud_rate: 9600
  parity: EVEN
```

Yes, we loose logging on the default USB port, but hey, who cares! We have logging over WIFI.
(and a fallback on Pin GPIO2 if we would ever need it).

**No level shifter**

Next, I wanted to skip the level shifter. I don't think it's really needed, and here's why: 

1) The ESP is 5v tolerant on it's IO pins.
2) Even if it's not (since the internet is 50/50 on this one) we can fix this.

Please note! This trick works because the Panasonic AC has resistors in series with it's TX and RX lines!

- For TX line on the ESP, we don't have to change anything. We can drive the RX line of the AC directly. This line is pulled-up by a resistor in the AC, and the ESP will simply pull it down hard when sending signals. The ESP's internal clamping diodes will make sure the voltage on this line never reache a too high value (also because of the series resistor on the line at AC side).
If you are really worried about your $3 module, add a 3v3 zener-diode to GND for this task.

- For the RX line on the ESP, we have to solder a 1k resistor between GND and RX on the ESP Side. The TX line of the AC also has a series resistor, but.. there is also a pull-up resistor on the NodeMCU (because this line is also still attached to the usb2serial chip of the NodeMCU module. The combination leads to the situation whereby the voltage won't go low enough when the AC pulls this line low.
To counter this effect, adding a 1K resistor to GND will shift this line's voltage more towards ground (like a voltage divider). Now, this line won't go higher then 3.3V. This line won't go to GND completely (because of the series resistor) so to be even more on the safe side around this low-voltage, you can go as low as 500Ohm's for this resistor if your NodeMCU is very picky.

P.S. 

For the fanboys who read the ESP's 8266 datasheet:
Yes, you can move the hardware UART to pin GPIO13 and 15 instead of GPIO3 and GPIO1. But.. Your ESP won't boot, because 

![image](https://user-images.githubusercontent.com/26247804/122993202-54c30c00-d3a7-11eb-9524-4a406c81475a.png)
https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

So, connecting your AC (with idle-high tx and rx lines) to this pin will prevent booting your ESP. It's a pity, because from an electrical perspective, this would be the better option.

I also tried D4 and D5 pins with a soft-uart, but couldn't get it to work.

**Comment by DomiStyle** [comment]
Good to know that it works, logging via USB isn't needed anyway most of the time.

> I also tried D4 and D5 pins with a soft-uart, but couldn't get it to work.

I'm surprised that it didn't work since the AC uses a fairly low baudrate of 9600, nothing a ESP8266 should struggle with.

The ESP8266 and ESP32 are both 5V tolerant, but it's out of spec so I still recommend a logic converter since it's not really complicated to connect through it and they are cheap.

**Comment by Expaso** [comment]
Agreed, if you have a logic converter, that is the best option. 
Problem was, I only had 2 left, and I needed to replace 4 wifi units.

I will retry the soft uart option using a scope, see if I can find anything weird.

Could you clarify out of spec? I always learned that TTL 5v and 3v3 were digitally compatible: https://learn.sparkfun.com/tutorials/logic-levels/all

**Comment by DomiStyle** [comment]
Out of spec for the ESP8266 data sheet, which lists a working voltage of 2.5V to 3.6V. Doesn't really matter if it works though.

**Comment by Expaso** [comment]
Ah you mean that.

For the VSS, the nodemcu has ofcourse its own 3.3v regulator., so you will always stay in-spec there. 

For the IO, above measures will make sure you also stay within specs, because of the 1k resistor on the RX line (forming a voltage divider) and the 3.3v zener on the TX line.
No 5v will ever reach 3.6v or higher on any pin if you take these measures.

Indeed, working out of specs is asking for trouble, so I value your caution.

**Comment by foxy82** [comment]
Is it possible to consolidate this info into README.md? Or perhaps better an esp8266.md doc linked from README rather than in the issue tracker? I'm going to look to try this as soon as I can.

**Comment by foxy82** [comment]
This worked for me I just needed a 470 ohm resistor instead of the 1k mentioned (I didn't have any 500 ohms to hand).

**Comment by Sashik259** [comment]
> 



> I confirm that it works fine as sad and it's possible to leave UART0 to debug logging. I've used GPIO13 for RX and GPIO2 for TX transmission

Do you use logic converter? I use Wemos D1 mini with logic converter and GPO1 for TX and GPIO3 for RX, but it doesnt work (no reply for commands, no status receiving from AC). I've opened an issue [here](https://github.com/DomiStyle/esphome-panasonic-ac/issues/54). 

Can you help me to fix it?

**Comment by kostrum** [comment]
Hi
@Expaso , could you share your full script for this integration for nodeMCU. Trying to follow your steps but still can't understand why it doesn't work...

**Comment by Expaso** [comment]
Yeah sure!

```
substitutions:
  devicename: airco-zolderkamer
  use_address: $devicename.local
  human_devicename: Airco Zolderkamer
 
esp8266:
  board: nodemcuv2

esphome:
  name: $devicename
  
packages:
  device_base: !include common/device_base.yaml
  wifi: !include common/wifi.yaml
  sensor_base: !include common/sensor_base.yaml

  # Enable logging
logger:
  hardware_uart: UART1 #Uses D4 (GPIO2) as LOG output!

uart:
  rx_pin: GPIO3 
  tx_pin: GPIO1 
  id: ac_uart
  baud_rate: 9600
  parity: EVEN

# Pull in the AC external component
external_components:
  source: github://DomiStyle/esphome-panasonic-ac
  components: [panasonic_ac]

climate:
  - platform: panasonic_ac
    name: ${human_devicename}
    # For CZ-TACG1
    # type: cnt

    # For DNSK-P11
    type: wlan

    horizontal_swing_select:
      name: ${human_devicename} Horizontal Swing Mode
    vertical_swing_select:
      name: ${human_devicename} Vertical Swing Mode
    outside_temperature:
      name: ${human_devicename} Outside Temperature

    # Enable as needed
    #eco_switch:
    #  name: Panasonic AC Eco Switch
    nanoex_switch:
      name: ${human_devicename} NanoeX Switch
    #mild_dry_switch:
    #  name: Panasonic AC Mild Dry Switch

    # Useful when the ac does not report a current temperature (CZ-TACG1 only)
    # current_temperature_sensor: temperature_sensor_id

```

Pay special attention to the logger! I use the hardware uart of that on, and move the logger out of the way.
