### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by sygys** [DomiStyle/esphome-panasonic-ac#80]
It seems there are errors in the github repository.

I get the following error when trying to update:
![Knipsel](https://user-images.githubusercontent.com/73538763/209994110-3335d832-eb57-4514-b55c-0287027a002e.JPG)

im using the github repo to get the latest info:

```
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  parity: EVEN

external_components:
  source: github://DomiStyle/esphome-panasonic-ac@dev-cztacg1
  components: [panasonic_ac]


climate:
  - platform: panasonic_ac
    # For CZ-TACG1
    # type: cnt

    # For DNSK-P11
    type: wlan

    name: Panasonic AC
    horizontal_swing_select:
      name: Panasonic AC Horizontal Swing Mode
    vertical_swing_select:
      name: Panasonic AC Vertical Swing Mode
    outside_temperature:
      name: Panasonic AC Outside Temperature
```

i think select is no longer a valid option?

i also get this error at the end
![Knipsel](https://user-images.githubusercontent.com/73538763/209998481-4e9491f5-0306-4f68-87e5-2cbc22c94674.JPG)
